AWSTemplateFormatVersion: 2010-09-09
Description: Template to create a web server with an EC2 instance

Parameters:
  OwnerTagName: 
    Type: String
    Default: Maria_Moreno
    Description: Value of the "Owner" tag to be applied to the resources
  
  MyIP:
    Type: String
    Default: 2.138.231.141/32
    Description: Your public IP address

  VPC:
    Type: AWS::EC2::VPC::Id
    Default: vpc-03fdd3b33e6bc9591
    Description: ID of the VPC to associate with the security groups

  PublicSubnet:
    Type: AWS::EC2::Subnet::Id
    Default: subnet-05a69f75c7584847b
    Description: ID of the public subnet 

  AvailabilityZone:
    Type: String
    Default: eu-west-1a
    Description: Availability zone where you want to locate your resources



Resources:

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group that enables ssh and http from my IP
      GroupName: srs-cloud-sandbox-mmr-sg
      SecurityGroupIngress: 
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref MyIP
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: !Ref MyIP
      Tags: 
        - Key: Owner
          Value: !Ref OwnerTagName
      VpcId: !Ref VPC

  EFS:
    Type: AWS::EFS::FileSystem
    Properties:
      FileSystemTags: 
        - Key: Name
          Value: srs-cloud-sandbox-mmr-efs
        - Key: Owner
          Value: !Ref OwnerTagName


  MountTarget:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref EFS 
      IpAddress: "String"
      SecurityGroups: 
         [!Ref SecurityGroup]
      SubnetId: !Ref PublicSubnet 
      

  EC2:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: !Ref AvailabilityZone
      ImageId: ami-0f007bf1d5c770c6e
      InstanceType: "t2.micro"
      KeyName: mmr-key-pair
      SecurityGroupIds: 
       [!Ref SecurityGroup] 
      SubnetId: !Ref PublicSubnet
      #Creamos el volumen EBS
      BlockDeviceMappings:
        - DeviceName: /dev/xvdf
          Ebs:
            VolumeSize: 2
            VolumeType: gp3
          Tags: 
          - Key: Name
            Value: srs-cloud-sandbox-mmr-ebs
          - Key: Owner
            Value: !Ref OwnerTagName
      Tags: 
        - Key: Owner
          Value: !Ref OwnerTagName
        - Key: Name
          Value: srs-cloud-sandbox-mmr-ec2
      UserData: 
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          yum install -y amazon-efs-utils httpd
          mkdir /mnt/efs
          echo "${EFS}.efs.eu-west-1.amazonaws.com:/ /mnt/efs efs defaults,_netdev 0 0" >> /etc/fstab
          mount -a
          systemctl enable httpd
          systemctl start httpd
          echo "<h1>Hello world from $(hostname)!</h1>" > /var/www/html/index.html


