# Last modified by Sergio Misas 14/05/2024
# This yaml creates an EC2 instance with a security group that allows the owner to connect via ssh
# It also mounts a EFS filesystem and an EBS volume to the instance
AWSTemplateFormatVersion: 2010-09-09

Parameters: 
  
  OwnerName:
    Description: Value of the tag Name
    Type: String
    Default: Sergio Misas

  OwnerIP:
     Description: IP of the owner
     Type: String
    
  VPCId: 
    Description: Id of the VPC in which all the content is going to be located 
    Type: AWS::EC2::VPC::Id
    Default: vpc-03fdd3b33e6bc9591

  SubnetId:
    Description: Id of the subnet where the content located
    Type: AWS::EC2::Subnet::Id
    Default: subnet-05a69f75c7584847b

  AvailabilityZone:
    Description: Availability zone where the resources are located
    Type: AWS::EC2::AvailabilityZone::Name
    Default: eu-west-1a

Resources:
  
  # Security group that allows the owner to connect via ssh
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group that lets only the owners IP
      GroupName: srs-cloud-sandbox-smv-sg
      SecurityGroupIngress: 
        - IpProtocol: 
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref OwnerIP #The IP of the owner 
      Tags: 
        - Key: Owner
          Value: !Ref OwnerName
        - Key: Name
          Value: srs-cloud-sandbox-smv-sg
      VpcId: !Ref VPCId #Id of the VPC in which the content is going to be located
      
  # EC2 instance located in the VPC and Subnet from the parameters, runs a command that mounts the EBS and EFS
  InstaciaEc2:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: !Ref AvailabilityZone #Availability zone of the subnet in which the instance is located
      ImageId: ami-0f007bf1d5c770c6e #Amazon-Linux
      InstanceType: "t2.micro"
      KeyName: KeyPairSergioM
      Tags: 
        - Key: Owner
          Value: !Ref OwnerName
        - Key: Name
          Value: srs-cloud-sandbox-smv-ec2
      SecurityGroupIds:
       [!Ref SecurityGroup] #Security group that lets the owner connect via ssh
      SubnetId: !Ref Subnet #Subnet in which the instance is located
      Volumes:
           - !Ref EbsVolume: 
             Device: "xvdb"
      UserData: "cd .. & cd .. & sudo mkdir vol & sudo file -s /dev/xvdb & sudo mkfs -t xfs /dev/xvdb & sudo mount /dev/xvdb /vol" #Format and Mount commands

  # EBS volume with a size of 4 GB located in the same Availability zone as the instance
  EbsVolume:
    Type: AWS::EC2::Volume
    Properties:
      AutoEnableIO: false
      AvailabilityZone: !Ref AvailabilityZone #Availability zone of the subnet in which the volume is located
      Encrypted: false
      Iops: 3000
      MultiAttachEnabled: false
      Size: 4 #Size in GB 
      Tags: 
        - Key: Owner
          Value: !Ref OwnerName
        - Key: Name
          Value: srs-cloud-sandbox-smv-ebs
      VolumeType: "gp3"
  
  # EFS filesystem located in the same Availability zone as the instance
  EfsFileSystem:
    Type: AWS::EFS::FileSystem
    Properties:
      AvailabilityZoneName: !Ref AvailabilityZone #Availability zone of the subnet in which the filesystem is located
      BypassPolicyLockoutSafetyCheck: false
      Encrypted: false
      FileSystemPolicy: JSON
      FileSystemTags: 
        Owner: !Ref OwnerName
      Tags: 
        - Key: Owner
          Value: !Ref OwnerName
        - Key: Name
          Value: srs-cloud-sandbox-smv-efs

      